name: fcm_notification_service
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_remote_config: ^6.1.1
  firebase_analytics: ^12.0.0
  firebase_messaging: ^16.1.0

  # Notification
  flutter_local_notifications: ^18.0.1

  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1

  # Navigation
  go_router: ^17.0.1

  # Dependency Injection
  get_it: ^9.2.0

  # Storage
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5

  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  



flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
